project:
  type: book
  output-dir: docs
##include-in-header: custom-head.html

book:
  title: "MSBA Bootcamp"
  author: "Pamela Schlosser"
  date: "11/18/2025"
  chapters:
    - index.qmd
    - introR.qmd
    - descriptives.qmd
    - dataprep.qmd
    - mathnotation.qmd
    - advmath.qmd
    - pythonsetup.qmd
    - datastructures.qmd
    - functions.qmd
    - numpypandas.qmd
    - sql.qmd
    - summary.qmd
    - references.qmd


format:
  html:
    css: styles.css
    number-sections: false
    toc: true
    toc-depth: 3
    toc-title: "Table of Contents"

editor: visual



